CREATE TABLE Categories (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE Articles (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  category_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES Categories(id)
);

CREATE TABLE Tags (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE ArticleTags (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  article_id INTEGER,
  tag_id INTEGER,
  FOREIGN KEY (article_id) REFERENCES Articles(id),
  FOREIGN KEY (tag_id) REFERENCES Tags(id)
);