"""add age to users

Revision ID: 03695f9ccc3d
Revises: b6ad09cd3858
Create Date: 2025-03-26 13:41:49.117405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03695f9ccc3d'
down_revision = 'b6ad09cd3858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
